name: Generate JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true

      - name: Run generate-json.py
        run: python generate-json.py
        continue-on-error: true

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate JSON files" && git push)
        continue-on-error: true

      - name: Check for errors
        if: failure()
        run: |
          echo "Workflow failed. Printing logs for debugging:"
          echo "Python version:"
          python --version
          echo "Pip list:"
          pip list
          echo "Contents of requirements.txt:"
          cat requirements.txt
          echo "Contents of generate-json.py:"
          cat generate-json.py
          echo "Git status:"
          git status
          exit 1
